fields:
  project_name: customfield_16501
  branch_name: customfield_16507
  dispensation_duration: customfield_17007
  package_name_or_versions : customfield_17009
  comment: customfield_16930
  # vulnerability_ids: customfield_17009 # sast field unavailable